In [2]:
import matplotlib.pyplot as plt
from sklearn import metrics
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
from sklearn.metrics import RocCurveDisplay
import pickle
import os

def report(y_true,outputs,path):
  RocCurveDisplay.from_predictions(
    y_true.ravel(),
    outputs.ravel(),
    name="micro-average OvR",
    color="darkorange",
    plot_chance_level=True,
  )
  class_names = ["bend",
    "crouch",
    "sit",
    "stand",
    "walk",
    "drive",
    "lift",
    "pull",
    "push",
    "put down",
    "overhead lift",
    "reaching"]
  
  labels = [1,2,3,4,5,6,7,8,9,10,11,12]
  plt.axis("square")
  plt.xlabel("False Positive Rate")
  plt.ylabel("True Positive Rate")
  plt.title("Micro-averaged One-vs-Rest\nReceiver Operating Characteristic")
  plt.legend()
  plt.savefig(os.path.join(path,'ROC.png'))
  plt.close()
  plt.figure().set_figheight(20)
  cm = confusion_matrix(np.argmax(y_true,axis = -1),np.argmax(outputs,axis = -1),labels = labels)
  cm = ConfusionMatrixDisplay(cm,display_labels=class_names).plot()
  plt.xticks(rotation='vertical')
  plt.gcf().set_size_inches(10, 10)
  plt.savefig(os.path.join(path,'confusion_matrix.png'))

if __name__ == '__main__':
  OUTPUT_PATH = "/home/ubuntu/Rumman/mmaction2/work_dirs/slow_fast_test_weller/results"
  file = open('/home/ubuntu/Rumman/mmaction2/work_dirs/slow_fast_test_weller/test.pkl', 'rb')
  data = pickle.load(file)
  file.close()
  outputs = []
  y_true= []
  for i,sample in enumerate(data):
    for output,label in zip(sample["pred_instances"]["scores"],sample["gt_instances"]["labels"]):
      outputs.append(output)
      y_true.append(label)
  # report(np.array(y_true),np.array(outputs),OUTPUT_PATH)

In [6]:
y_true[0]

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
count = 0
for x,y in zip(y_true,outputs):
    if x[10] == 1:
        print(x)
        print(y)
print(count)
# 0:1184  1:0  2:0  3:156  4:1159  5:688  6:43 7:0 8-14:0

tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5531, 0.2311, 0.0011, 0.0101, 0.3897, 0.2050, 0.0177, 0.0111, 0.0030,
        0.0018, 0.0110, 0.0018, 0.0176])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5531, 0.2311, 0.0011, 0.0101, 0.3897, 0.2050, 0.0177, 0.0111, 0.0030,
        0.0018, 0.0110, 0.0018, 0.0176])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5531, 0.2311, 0.0011, 0.0101, 0.3897, 0.2050, 0.0177, 0.0111, 0.0030,
        0.0018, 0.0110, 0.0018, 0.0176])


tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5531, 0.2311, 0.0011, 0.0101, 0.3897, 0.2050, 0.0177, 0.0111, 0.0030,
        0.0018, 0.0110, 0.0018, 0.0176])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5531, 0.2311, 0.0011, 0.0101, 0.3897, 0.2050, 0.0177, 0.0111, 0.0030,
        0.0018, 0.0110, 0.0018, 0.0176])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5531, 0.2311, 0.0011, 0.0101, 0.3897, 0.2050, 0.0177, 0.0111, 0.0030,
        0.0018, 0.0110, 0.0018, 0.0176])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5531, 0.2311, 0.0011, 0.0101, 0.3897, 0.2050, 0.0177, 0.0111, 0.0030,
        0.0018, 0.0110, 0.0018, 0.0176])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5525, 0.2342, 0.0011, 0.0103, 0.3922, 0.2026, 0.0182, 0.0113, 0.0030,
        0.0018, 0.0112, 0.0019, 0.0177])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0.5525, 0.2342, 0.001

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image

def draw_and_display_bounding_box(image_path, bounding_box, output_path):
    # Open the image
    image = Image.open(image_path)

    # Create figure and axes
    fig, ax = plt.subplots()

    # Display the image
    ax.imshow(image)

    # Unpack the bounding box coordinates
    x_min, y_min, x_max, y_max = bounding_box

    # Create a rectangle patch
    rect = patches.Rectangle((x_min, y_min), x_max - x_min, y_max - y_min, linewidth=2, edgecolor='r', facecolor='none')

    # Add the rectangle to the Axes
    ax.add_patch(rect)

    # Display the image with the bounding box
    plt.show()

    # Save the image with the bounding box
    image.save(output_path)

# Example usage
image_path = "/home/ubuntu/Furqan/new_dataset/20231004-activity-all-annotated-tasks/activity_nov2022_150402-150902_2/img_00000.jpg"
bounding_box_coordinates = (0.026,0.166,0.077,0.357)  # Replace with your bounding box coordinates
output_path = "path/to/your/output/image_with_bbox.jpg"
draw_and_display_bounding_box(image_path, bounding_box_coordinates, output_path)
